CREATE TABLE COMUNA(
    ID_COMUNA NUMBER(3) CONSTRAINT pk_comuna PRIMARY KEY NOT NULL,
    NOMBRE_COMUNA VARCHAR2(30) NOT NULL
);

CREATE TABLE ESTADO_CIVIL(
    ID_ESTCIVIL NUMBER(1) CONSTRAINT pk_estado_civil PRIMARY KEY NOT NULL,
    DESC_EST_CIVIL VARCHAR2(25) NOT NULL
);

CREATE TABLE EMPLEADO(
    NUMRUT_EMP NUMBER(10) CONSTRAINT pk_rut PRIMARY KEY NOT NULL,
    DVRUT_EMP VARCHAR2(1) NOT NULL,
    APPATERNO VARCHAR2(15) NOT NULL,
    APMATERNO_EMP VARCHAR2(15) NOT NULL,
    NOMBRE_EMPLEADO VARCHAR2(25) NOT NULL,
    DIRECCION_EMP VARCHAR2(60) NOT NULL,
    ID_ESTCIVIL NUMBER(1) NOT NULL,
    FONOFIJO_EMP VARCHAR2(15) NOT NULL,
    CELULAR_EMP VARCHAR2(15),
    FECNAC_EMP DATE NOT NULL,
    FECING_EMP DATE NOT NULL,
    SULEDO_EMP NUMBER(7) NOT NULL,
    ID_COMUNA NUMBER(3) NOT NULL,
    ID_CATEGORIA_EMP NUMBER(1),
    CONSTRAINT fk_id_estcivil FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL),
    CONSTRAINT fk_id_comuna FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA)
);

CREATE TABLE PROPIETARIO(
    NUMRUT_PROP NUMBER(10) CONSTRAINT pk_numrut PRIMARY KEY NOT NULL,
    DVRUT_PROP VARCHAR2(1) NOT NULL,
    APPATERNO_PROP VARCHAR2(15) NOT NULL,
    APMATERNO_PROP VARCHAR2(15) NOT NULL,
    NOMBRE_PROP VARCHAR2(60) NOT NULL,
    DIRECCION_PROP VARCHAR2(60) NOT NULL,
    ID_ESTCIVIL NUMBER(1) NOT NULL,
    FONOFIJO_PROP VARCHAR2(15) NOT NULL,
    CELULAR_PROP VARCHAR2(15),
    ID_COMUNA NUMBER(3) NOT NULL,
    CONSTRAINT fk_propietario_comuna FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
    CONSTRAINT fk_propietario_estado_civil FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL)
);

CREATE TABLE CLIENTE(
    NUMRUT_CLI NUMBER(10) NOT NULL,
    DVRUT_CLI CHAR(1) NOT NULL,
    APPATERNO_CLI VARCHAR2(15) NOT NULL,
    APMATERNO_CLI VARCHAR(15),
    NOMBRE_CLI VARCHAR2(25) NOT NULL,
    DIRECCION_CLI VARCHAR2(60) NOT NULL,
    ID_ESTCIVIL NUMBER(1) NOT NULL,
    FONOFIJO_CLI NUMBER(15) NOT NULL,
    CELULAR_CLI NUMBER(15),
    RENTA_CLI NUMBER(7),
    CONSTRAINT pk_cliente PRIMARY KEY (NUMRUT_CLI)
);

ALTER TABLE CLIENTE ADD CONSTRAINT fk_cliente FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL);

CREATE TABLE TIPO_PROPIEDAD(
    ID_TIPO_PROPIEDAD CHAR(1),
    DES_TIPO_PROPIEDAD VARCHAR2(30) NOT NULL
);

ALTER TABLE TIPO_PROPIEDAD ADD CONSTRAINT pk_tipo_propiedad PRIMARY KEY (ID_TIPO_PROPIEDAD);


CREATE TABLE PROPIEDAD(
    NRO_PROPIEDAD NUMBER(6) CONSTRAINT pk_nro_propiedad PRIMARY KEY NOT NULL,
    DIRECCION_PROPIEDAD VARCHAR2(60) NOT NULL,
    SUPERFICIE NUMBER(8,2) NOT NULL,
    NRO_DORMITORIOS NUMBER(1),
    NRO_BANOS NUMBER(1),
    VALOR_ARRIENDO NUMBER(7) NOT NULL,
    VALOR_GASTO_COMUN NUMBER(6),
    ID_TIPO_PROPIEDAD CHAR(1) NOT NULL,
    ID_COMUNA NUMBER(3) NOT NULL,
    NUMRUT_PROP NUMBER(10) NOT NULL,
    NUMRUT_EMP NUMBER(10) NOT NULL,
    CONSTRAINT fk_idtipopropiedad FOREIGN KEY (ID_TIPO_PROPIEDAD) REFERENCES TIPO_PROPIEDAD(ID_TIPO_PROPIEDAD),
    CONSTRAINT fk_idcomuna FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
    CONSTRAINT fk_numrut_prop FOREIGN KEY (NUMRUT_PROP) REFERENCES PROPIETARIO(NUMRUT_PROP),
    CONSTRAINT fk_propiedadempleado FOREIGN KEY (NUMRUT_EMP) REFERENCES EMPLEADO(NUMRUT_EMP)
);


CREATE TABLE PROPIEDAD_ARRENDADA(
    NRO_PROPIEDAD NUMBER(6) NOT NULL,
    FECINI_ARRIENDO DATE NOT NULL,
    FECTER_ARRIENDO DATE,
    NUMRUT_CLI NUMBER(10) NOT NULL,
    CONSTRAINT PK_DOBLE_PROPIEDAD_ARRE PRIMARY KEY (NRO_PROPIEDAD, FECINI_ARRIENDO),
    CONSTRAINT FK_PROPIEDAD_ARRE_CLIENTE FOREIGN KEY (NUMRUT_CLI) REFERENCES CLIENTE(NUMRUT_CLI)
);

ALTER TABLE PROPIEDAD_ARRENDADA ADD CONSTRAINT FK_PRO_TIPO_PRO FOREIGN KEY (NRO_PROPIEDAD) REFERENCES PROPIEDAD(NRO_PROPIEDAD);


INSERT INTO COMUNA VALUES(80, 'Las Condes');
INSERT INTO COMUNA VALUES(81, 'Providencia');
INSERT INTO COMUNA VALUES(82, 'Santiago');
INSERT INTO COMUNA VALUES(83, 'Nunoa');
INSERT INTO COMUNA VALUES(84, 'Vitacura');


INSERT INTO ESTADO_CIVIL VALUES(1, 'Soltero');
INSERT INTO ESTADO_CIVIL VALUES(2, 'Casado');
INSERT INTO ESTADO_CIVIL VALUES(3, 'Separado');
INSERT INTO ESTADO_CIVIL VALUES(4, 'Viudo');
INSERT INTO ESTADO_CIVIL VALUES(5, 'Divorciado');

INSERT INTO TIPO_PROPIEDAD VALUES('A', 'Casa sin Amoblar');
INSERT INTO TIPO_PROPIEDAD VALUES('B', 'Casa Amoblada');
INSERT INTO TIPO_PROPIEDAD VALUES('C', 'Departamento sin Amoblar');
INSERT INTO TIPO_PROPIEDAD VALUES('D', 'Departamento Amoblado');
INSERT INTO TIPO_PROPIEDAD VALUES('E', 'Local Comercial');


INSERT INTO CLIENTE VALUES(10639521, '0', 'UVAL', 'RIQUELME', 'MIGUEL', 'SAN PABLO B/2 DPTO. 12', 5, 26439756, 52710253, 1300000);



