ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER JOSE
IDENTIFIED BY JOSE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER JOSE QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO JOSE;
GRANT "RESOURCE" TO JOSE;