--FORMA MANUAL DE CREAR USUARIO--

--COMANDO PARA PERMITIR AL USUARIO SYS EJECUTAR CODIGO
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--PROCESO DE CREACIÓN DE NUEVO USUARIO
CREATE USER JOSE
IDENTIFIED BY JOSE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--ESPECIFICAR CUANTO ESPACIO PUEDE USAR JOSE DE LA CARPETA USERS
ALTER USER JOSE QUOTA UNLIMITED ON USERS;

--PERMISOS DE CONECTARSE A UNA BASE DE DATOS
GRANT CREATE SESSION TO JOSE;

--PERMISOS DE CRUD DE TABLAS Y DATOS
GRANT "RESOURCE" TO JOSE;
