--CASO 01:

--CONOCER TABLAS A TRABAJAR:

SELECT * FROM EMPLEADO;
DESC EMPLEADO;

--CONSULTA CASO 01
SELECT 'El empleado ' || NOMBRE_EMP || ' ' || APPATERNO_EMP || ' ' || APMATERNO_EMP|| 'Nacio el ' || TO_CHAR(FECNAC_EMP, 'DD/MM/YYYY') AS "LISTADO DE CUMPLEAÑOS" FROM EMPLEADO;


--CASO 2:

SELECT * FROM CLIENTE;
DESC CLIENTE;

SELECT 
    TO_CHAR(NUMRUT_CLI, '999G999G999')|| '-' || DVRUT_CLI AS "Rut cliente",
    INITCAP(NOMBRE_CLI || ' ' || APPATERNO_CLI || ' ' || APMATERNO_CLI) AS "Nombre cliente",
    TO_CHAR(RENTA_CLI, '$999G999G999') AS "RENTA",
    FONOFIJO_CLI AS "FONO FIJO",
    CELULAR_CLI AS "FONO MOVIL"
FROM 
    CLIENTE
ORDER BY NOMBRE_CLI ASC, APPATERNO_CLI ASC, APMATERNO_CLI ASC;


--CASO 3:

SELECT * FROM EMPLEADO;
DESC EMPLEADO;

SELECT 
    INITCAP(NOMBRE_EMP || ' ' || APPATERNO_EMP || ' ' || APMATERNO_EMP) AS "NOMBRE EMPLEADO",
    TO_CHAR(SUELDO_EMP, '$999G999G999') AS "SUELDO",
    TO_CHAR(ROUND(SUELDO_EMP * 0.5), '$999G999G999') AS "BONO EMPLEADO",
    TO_CHAR(ROUND(SUELDO_EMP + (SUELDO_EMP * 0.5)), '$999G999G999') AS "BONO CON SUELDO"
FROM
    EMPLEADO;